apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rl5et0bdh-python 
  janus-idp.io/tekton: rl5et0bdh-python
  backstage.io/kubernetes-id: rl5et0bdh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rl5et0bdh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml