apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rl5et0bdh-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-04645c96f9.8vyt.p3.openshiftapps.com/rhtap/rhtap-qe-python:4f455767e9a768bb09519a58b91d165936333e40@sha256:1b8a5cc6c8e74c81d4f4b3f1b3f96c9802339ce2cfb94ec4399af342bad802c9
          name: container-image
